# Generated by Django 4.2.2 on 2023-07-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Procesando'), ('sending', 'En envío'), ('received', 'Recibida'), ('paid', 'Pagada')], default='processing', max_length=30),
        ),
    ]
