# Generated by Django 4.2.2 on 2023-06-27 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el siguiente formato: '+código de país-número de área-número de teléfono'.", regex='[+535]\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el siguiente formato: '+código de país-número de área-número de teléfono'.", regex='[+535]\\d{10}$')]),
        ),
    ]
