# Generated by Django 4.2.2 on 2023-07-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='address',
        ),
    ]
